# -- Theme Options --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "congo"
defaultAppearance = "dark"   
autoSwitchAppearance = true    

disableImageOptimization = false

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateUpdated = false
  showAuthor = true
  showHero = false
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = true
  showComments = false
  sharingLinks = ["github", "medium", "tryhackme", "outlook"]

[list]
  showHero = false
  showBreadcrumbs = false
  showSummary = true
  showViews = false
  showLikes = false
  showTableOfContents = false
  groupByYear = true

[sitemap]
  excludedKinds = []

[footer]
  showAppearanceSwitcher = true

[homepage]
  layout = "profile"     
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "/posts/"
  cardView = true
